"""Add foto_profil

Revision ID: 20b7543ede30
Revises: d494b5cbd835
Create Date: 2026-06-05 17:27:56.954550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b7543ede30'
down_revision = 'd494b5cbd835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_profil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.drop_column('foto_profil')

    # ### end Alembic commands ###
