"""skema awal gonanku

Revision ID: d494b5cbd835
Revises: 
Create Date: 2026-06-05 17:07:14.641369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd494b5cbd835'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('kata_sandi_hash', sa.String(length=255), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pengguna_email'), ['email'], unique=True)

    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pengguna_id', 'nama', name='uq_kategori_pengguna_nama')
    )
    with op.batch_alter_table('kategori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kategori_pengguna_id'), ['pengguna_id'], unique=False)

    op.create_table('riwayat_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('jawaban', sa.Text(), nullable=True),
    sa.Column('berkas_hasil', sa.String(length=255), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riwayat_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riwayat_chat_dibuat_pada'), ['dibuat_pada'], unique=False)
        batch_op.create_index(batch_op.f('ix_riwayat_chat_pengguna_id'), ['pengguna_id'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=80), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pengguna_id', 'nama', name='uq_tag_pengguna_nama')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_pengguna_id'), ['pengguna_id'], unique=False)

    op.create_table('berkas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('kode_arsip', sa.String(length=20), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('nama_file_asli', sa.String(length=255), nullable=False),
    sa.Column('tipe_file', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('ukuran_file', sa.BigInteger(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('tanggal_upload', sa.DateTime(), nullable=False),
    sa.Column('tanggal_momen', sa.Date(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.Column('telegram_file_unique_id', sa.String(length=120), nullable=True),
    sa.Column('judul_ai', sa.String(length=255), nullable=True),
    sa.Column('kategori_ai', sa.String(length=120), nullable=True),
    sa.Column('ringkasan_ai', sa.Text(), nullable=True),
    sa.Column('peringatan_privasi', sa.String(length=255), nullable=True),
    sa.Column('tingkat_kepercayaan_ai', sa.Float(), nullable=True),
    sa.Column('teks_ekstraksi', sa.Text(), nullable=True),
    sa.Column('status_privasi', sa.String(length=20), nullable=False),
    sa.Column('status_berkas', sa.String(length=20), nullable=False),
    sa.Column('status_ai', sa.String(length=20), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.Column('diperbarui_pada', sa.DateTime(), nullable=False),
    sa.Column('dihapus_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_arsip')
    )
    with op.batch_alter_table('berkas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_berkas_dihapus_pada'), ['dihapus_pada'], unique=False)
        batch_op.create_index(batch_op.f('ix_berkas_kategori_id'), ['kategori_id'], unique=False)
        batch_op.create_index('ix_berkas_pengguna_dihapus', ['pengguna_id', 'dihapus_pada'], unique=False)
        batch_op.create_index(batch_op.f('ix_berkas_pengguna_id'), ['pengguna_id'], unique=False)
        batch_op.create_index('ix_berkas_status', ['status_berkas'], unique=False)
        batch_op.create_index('ix_berkas_status_ai', ['status_ai'], unique=False)
        batch_op.create_index('ix_berkas_tanggal_momen', ['tanggal_momen'], unique=False)
        batch_op.create_index('ix_berkas_tanggal_upload', ['tanggal_upload'], unique=False)
        batch_op.create_index('ix_berkas_tipe', ['tipe_file'], unique=False)

    op.create_table('berkas_tag',
    sa.Column('berkas_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['berkas_id'], ['berkas.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('berkas_id', 'tag_id')
    )
    op.create_table('log_aktivitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('berkas_id', sa.Integer(), nullable=True),
    sa.Column('aksi', sa.String(length=60), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['berkas_id'], ['berkas.id'], ),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_aktivitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_aktivitas_berkas_id'), ['berkas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_aktivitas_dibuat_pada'), ['dibuat_pada'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_aktivitas_pengguna_id'), ['pengguna_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_aktivitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_aktivitas_pengguna_id'))
        batch_op.drop_index(batch_op.f('ix_log_aktivitas_dibuat_pada'))
        batch_op.drop_index(batch_op.f('ix_log_aktivitas_berkas_id'))

    op.drop_table('log_aktivitas')
    op.drop_table('berkas_tag')
    with op.batch_alter_table('berkas', schema=None) as batch_op:
        batch_op.drop_index('ix_berkas_tipe')
        batch_op.drop_index('ix_berkas_tanggal_upload')
        batch_op.drop_index('ix_berkas_tanggal_momen')
        batch_op.drop_index('ix_berkas_status_ai')
        batch_op.drop_index('ix_berkas_status')
        batch_op.drop_index(batch_op.f('ix_berkas_pengguna_id'))
        batch_op.drop_index('ix_berkas_pengguna_dihapus')
        batch_op.drop_index(batch_op.f('ix_berkas_kategori_id'))
        batch_op.drop_index(batch_op.f('ix_berkas_dihapus_pada'))

    op.drop_table('berkas')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_pengguna_id'))

    op.drop_table('tag')
    with op.batch_alter_table('riwayat_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riwayat_chat_pengguna_id'))
        batch_op.drop_index(batch_op.f('ix_riwayat_chat_dibuat_pada'))

    op.drop_table('riwayat_chat')
    with op.batch_alter_table('kategori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kategori_pengguna_id'))

    op.drop_table('kategori')
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pengguna_email'))

    op.drop_table('pengguna')
    # ### end Alembic commands ###
